kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: pod-web
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          image: anilappari/s1:1.007
          ports:
            - containerPort: 8080
